config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
  	resources :parts
  end

  root "tasks#index"

  match "tasks/:task_id/parts/:id/mark_complete", :to => "parts#mark_complete", :as => "part_completed", :via => :post
  match "tasks/refresh", :to => "tasks#refresh", :as => "refresh", :via => :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :parts, inverse_of: :task, :dependent => :delete_all
	accepts_nested_attributes_for :parts,
																reject_if: proc { |attributes| attributes['name'].blank? },
																allow_destroy: true

	validates :name, :start_date, :end_date, presence: true

	def start_time
		self.start_date
	end

	def end_time
		self.end_date
	end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :authentication_keys => [:username]

  has_many :tasks

  validates :username, uniqueness: true

  def email_required?
    false
  end
  
  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  	@task = Task.find(params[:task_id])
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_complete
  	@task = Task.find(params[:task_id])
  	@part = Part.find(params[:id])
  	@part.update_attribute(:completed, true)
  	redirect_to root_path, :notice => "#{@task.name}>#{@part.chapter}>#{@part.module}>#{@part.name} Completed!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:chapter, :module, :name, :hours, :minutes, :completed)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def refresh
    @tasks = current_user.tasks
    @tasks.each do |task|
      task.parts.each do |part|
        if part.completed
          part.destroy
        end
      end
    end
    redirect_to root_path, :notice => "Completed Tasks Removed!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :start_date, :end_date, :user_id, parts_attributes: [:id, :chapter, :module, :name, :hours, :minutes, :completed, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CPA Planner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <%= link_to "CPA Planner", root_path, :class => "navbar-brand page-scroll" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <% if user_signed_in? %>
                    <li>
                      <%= link_to 'New Task', new_task_path, :class => "page-scroll" %>
                    </li>
                    <li>
                      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                    </li>
                  <% else %>
                    <li>
                      <%= link_to 'Login', new_user_session_path %>
                    </li>
                    <li>
                      <%= link_to 'Sign Up', new_user_registration_path %>
                    </li>
                  <% end %>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>

    <header>
      <div class="header-content">
          <div class="header-content-inner">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
          </div>
      </div>
    </header>
  </body>
</html>

app/views/parts/show.html.erb
<table class="table">
	<thead>
		<tr>
			<th>Task</th>
			<th>Chapter</th>
			<th>Module</th>
			<th>Name</th>
			<th>Hours</th>
			<th>Minutes</th>
			<th>Completed</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @task.name %></td>
			<td><%= @part.chapter %></td>
			<td><%= @part.module %></td>
			<td><%= @part.name %></td>
			<td><%= @part.hours %></td>
			<td><%= @part.minutes %></td>
			<td><%= @part.completed ? "Yes" : "No" %></td>
		</tr>
	</tbody>
</table>

<% if @part.completed == false %>
	<%= link_to 'Mark Done', part_completed_path(@task, @part), :method => :post, class: "btn btn-primary btn-lg" %>
<% end %>
<br><br>
<%= link_to 'Back', tasks_path, class: "btn btn-default btn-md" %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class: "btn btn-primary btn-xs" %>
    <span class="calendar-title" style="font-size: 12pt;"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class: "btn btn-primary btn-xs" %>
  </div>

  <br>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>
  <hr>

  <h3>Parts</h3>
  <div id="parts">
    <%= f.simple_fields_for :parts do |part| %>
      <%= render 'part_fields', f: part %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Part', f, :parts, class: "btn btn-success btn-md" %><br><br>
    </div>  
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-lg" %><br><br>
  </div>
<% end %>

app/views/tasks/_part_fields.html.erb
<div class="nested-fields">
	<%= f.input :chapter %>
	<%= f.input :module %>
	<%= f.input :name %>
	<%= f.input :hours %>
	<%= f.input :minutes %>
	<%= f.input :completed, :as  => :hidden, :input_html => { :value => false }%>
	<%= link_to_remove_association "Remove Part", f, class: "btn btn-warning btn-md" %><br>
	<hr>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task, class: "btn btn-default btn-md" %> |
<%= link_to 'Back', tasks_path, class: "btn btn-default btn-md" %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table class="table">
  <thead>
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Start date</th>
      <th class="text-center">End date</th>
      <th class="text-center">Mins / Day</th>
      <th class="text-center">Days</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <% start = DateTime.now.to_date > task.start_date ? DateTime.now.to_date : task.start_date %>
      <% num_days = (task.end_date - start + 1).to_i %>

      <% total_minutes = 0 %>
      <% task.parts.each do |part| %>
        <% total_minutes += (part.hours * 60) + part.minutes %>
      <% end %>
      <% minutes_per_day = (total_minutes.to_f / num_days.to_f) %>

      <tr>
        <td><%= task.name %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= minutes_per_day.round %></td>
        <td><%= num_days %></td>
        <td><%= link_to 'Show', task, class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= month_calendar events: @tasks, attribute: :start_date, end_attribute: :end_date do |date, tasks| %>
  <%= date.day %><br>

  <% tasks.each do |task| %>
    <% start = DateTime.now.to_date > task.start_date ? DateTime.now.to_date : task.start_date %>
    <% num_days = (task.end_date - start + 1).to_i %>

    <% days_arr = [] %>
    <% first_available_day = 0 %>
    <% num_days.times do %>
      <% days_arr.push([]) %>
    <% end %>

    <% total_minutes = 0 %>
    <% task.parts.each do |part| %>
      <% total_minutes += (part.hours * 60) + part.minutes %>
    <% end %>
    <% minutes_per_day = (total_minutes.to_f / num_days.to_f) %>
    <% time_left_in_day = minutes_per_day %>

    <% parts = task.parts %>

    <% same_task = false %>

    <% while parts.count > 0 %>
      <% part = parts.first %>

      <% unless same_task %>
        <% min_todo = part.hours * 60 + part.minutes %>
      <% end %>

      <% if days_arr.count > first_available_day %>
        <% days_arr[first_available_day].push(part) %>
        <% same_task = true %>
      <% end %>

      <% if min_todo > time_left_in_day %>
        <% min_todo -= time_left_in_day %>
        <% time_left_in_day = minutes_per_day %>
        <% first_available_day += 1 %>
      <% else %>
        <% parts = parts.drop(1) %>
        <% same_task = false %>
        <% time_left_in_day -= min_todo %>

        <% if time_left_in_day <= 0 %>
          <% time_left_in_day = minutes_per_day %>
          <% first_available_day += 1 %>
        <% end %>
      <% end %>
    <% end %>

    <% days_from_start = (date - start).to_i %>
    <% days_arr[days_from_start] = days_arr[days_from_start] || [] %>
    <% days_arr[days_from_start].each do |p| %>
      <% next if days_from_start < 0 %>

      <%= link_to "#{p.chapter}>#{p.module}>#{p.name}:#{p.hours*60 + p.minutes}#{p.completed ? ' | DONE' : ''}", task_part_path(task, p), class: "btn btn-default btn-xs cal-content" %>
    <% end %>
  <% end %>
<% end %>

<br>

<%= link_to 'New Task', new_task_path, class: "btn btn-primary btn-xl page-scroll" %>

<br><br>

<%= link_to 'Refresh', refresh_path, :method => :post, class: "btn btn-primary btn-lg" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: "btn btn-default btn-md" %>

app/views/tasks/show.html.erb
<div class="well well-title">
  <h1><%= @task.name %></h1>

  <h3><%= @task.start_date.to_formatted_s :rfc822 %> - <%= @task.end_date.to_formatted_s :rfc822 %></h3>
</div>

<h3>Parts</h3>
<% @task.parts.each do |part| %>
	<div class="well">
	  <p>
	  	<%= part.chapter %> > <%= part.module %> > <%= part.name %>: <%= pluralize(part.hours * 60 + part.minutes, 'min') %>
	  </p>
	</div>
<% end %>

<%= link_to 'Edit', edit_task_path(@task), class: "btn btn-default btn-sm" %> |
<%= link_to 'Destroy', @task, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm" %>
<br><br>
<%= link_to 'Back', tasks_path, class: "btn btn-default btn-md" %>